### ISSUE TITLE
don't support output excel ?

### ISSUE THREAD

**Issue by etoanik** [subteno-it/openerp-jasperserver#5]

**Comment by etoanik** [comment]
I have setting an excel report, but it don't work. 
and throw exception.

**Comment by kryskool** [comment]
Can you retry with the last version ?

Regards,

**Comment by etoanik** [comment]
Thanks for repair

XLS       OK
DOCX   FAIL
XLSX     FAIL

**Comment by kryskool** [comment]
Hi @etoanik 

Thanks for testing

Which version of JasperServer you use ?

Regards,

**Comment by etoanik** [comment]
to kryskool

JasperServer v5.5.0

**Comment by kryskool** [comment]
Ok thanks, i'll retry with this version
